variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "disk_size" {}
variable "vm_name" {}
variable "cpu_count" {}
variable "memory" {}
variable "vm_count" {}
variable "tag_name" {}
